Repository ovh-ux/ng-ovh-sidebar-menu, pull requests merged in 2019-06, with the labels that each got.

#62 feat: add style for level 4 active items
  src/index.less
Labels: enhancement

#63 build: upgrade some devDependencies
  package.json
  src/list/item/directive.js
  yarn.lock
Labels: dependencies

#64 Release v8.3.0
  package.json
  src/index.less
  src/list/item/directive.js
  yarn.lock
Labels: release :package:

#69 fix: load subitems on search
  src/list/item/directive.js
  src/list/item/factory.js
Labels: bug

#70 Release v8.3.2
  src/list/item/directive.js
  src/list/item/factory.js
Labels: release :package:

#73 build(gitignore): add missing tools entry
  .gitignore
Labels: build

#74 fix(i18n): retrieve translations
  src/translations/Messages_de_DE.xml
  src/translations/Messages_en_ASIA.xml
  src/translations/Messages_en_AU.xml
  src/translations/Messages_en_SG.xml
  src/translations/Messages_es_US.xml
Labels: bug

#75 Release v8.3.3
  .gitignore
  src/translations/Messages_de_DE.xml
  src/translations/Messages_en_ASIA.xml
  src/translations/Messages_en_AU.xml
  src/translations/Messages_en_SG.xml
  src/translations/Messages_es_US.xml
Labels: release :package:
