Repository ovh-ux/ng-ovh-sidebar-menu, pull requests merged in 2020-01, with the labels that each got.

#111 feat: allow an item to be hidden
  src/list/item/factory.js
  src/list/template.html
Labels: enhancement

#112 Release v8.5.0
  README.md
  ROADMAP.md
  package.json
  rollup.config.js
  src/list/item/factory.js
  src/list/template.html
  yarn.lock
Labels: release

#115 fix(provider): consider parent to get path item
  src/provider.js
Labels: bug
